### ISSUE TITLE
Small Apothic Boss Gate causes the game to freeze

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadows-of-Fire/GatewaysToEternity#26]
When challenging the third stage of Small Apothic Boss Gate, the game will freeze permanently
No information appears in the log at the time of freezing
Strangely enough, when I found this problem, I opened a separate test module package and opened a Superflat world to test it, it can be summoned normally
But when I used a normal world to test it, the problem appeared
Apart from Apotheosis only Better Combat was installed

Apotheosis-1.19.2-6.2.1
GatewaysToEternity-1.19.2-3.2.0

**Comment by mechanizedmonk** [comment]
I also have this problem in the modpack "Medieval MC [FORGE] 1.19.2 v17 HF"

Apotheosis-1.19.2-6.2.1
GatewaysToEternity-1.19.2-3.2.0


"Server thread" prio=4 Id=254 RUNNABLE
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:114)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:19)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.CollisionGetter.m_45756_(CollisionGetter.java:51)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.CollisionGetter.m_45772_(CollisionGetter.java:40)
	at TRANSFORMER/gateways@3.2.0/shadows.gateways.gate.SpawnAlgorithms.openField(SpawnAlgorithms.java:65)
	at TRANSFORMER/gateways@3.2.0/shadows.gateways.gate.SpawnAlgorithms$$Lambda$42181/0x0000000804948000.spawn(Unknown Source)
	...

extended trace:
	at TRANSFORMER/gateways@3.2.0/shadows.gateways.gate.Wave.spawnWave(Wave.java:52)
	at TRANSFORMER/gateways@3.2.0/shadows.gateways.entity.GatewayEntity.spawnWave(GatewayEntity.java:193)
	at TRANSFORMER/gateways@3.2.0/shadows.gateways.entity.GatewayEntity.m_8119_(GatewayEntity.java:154)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel$$Lambda$52853/0x000000080552c978.accept(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_46653_(Level.java:457)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel$$Lambda$52776/0x0000000805515798.accept(Unknown Source)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer$$Lambda$51441/0x00000008053493a0.run(Unknown Source)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

**Comment by Shadows-of-Fire** [comment]
This was an apoth bug, fixed in 6.3.5
