### ISSUE TITLE
Mod keep freezing the server

### ISSUE THREAD

**Issue by SuperFurias** [Shadows-of-Fire/GatewaysToEternity#48]
I'm using the latest version of the mod (1.20.1, 4.2.3) inside the modpack Craft to Exile 2

When i open a gate, any gate, the server starts to lag A LOT, it happens at every wave, when killing the last mob, lags so much that it kicks every player out of the server

logs:

java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.checkValidFloatingPoint(Gson.java:444)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson$2.write(Gson.java:433)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson$2.write(Gson.java:419)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.toJson(Gson.java:825)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.toJson(Gson.java:795)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.toJson(Gson.java:742)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.toJson(Gson.java:719)
	at TRANSFORMER/library_of_exile@1.4.1/com.robertx22.library_of_exile.utils.LoadSave.Save(LoadSave.java:20)
	at TRANSFORMER/library_of_exile@1.4.1/com.robertx22.library_of_exile.components.EntityInfoComponent$DefaultImpl.serializeNBT(EntityInfoComponent.java:122)
	at TRANSFORMER/library_of_exile@1.4.1/com.robertx22.library_of_exile.components.EntityInfoComponent$DefaultImpl.serializeNBT(EntityInfoComponent.java:62)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:115)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:132)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20240_(Entity.java:1658)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.NbtPredicate.m_57485_(NbtPredicate.java:77)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.NbtPredicate.m_57477_(NbtPredicate.java:40)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.EntityPredicate.m_36607_(EntityPredicate.java:154)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition.test(LootItemEntityPropertyCondition.java:40)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition.test(LootItemEntityPropertyCondition.java:17)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.InvertedLootItemCondition.test(InvertedLootItemCondition.java:27)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.InvertedLootItemCondition.test(InvertedLootItemCondition.java:13)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.ContextAwarePredicate.m_285831_(ContextAwarePredicate.java:39)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.PlayerHurtEntityTrigger$TriggerInstance.m_60142_(PlayerHurtEntityTrigger.java:68)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.PlayerHurtEntityTrigger.m_60119_(PlayerHurtEntityTrigger.java:27)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:64)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.advancements.critereon.PlayerHurtEntityTrigger.m_60112_(PlayerHurtEntityTrigger.java:27)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1202)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Zombie.m_6469_(Zombie.java:267)
	at TRANSFORMER/gateways@4.2.3/dev.shadowsoffire.gateways.gate.Reward$EntityLootReward.generateLoot(Reward.java:175)
	at TRANSFORMER/gateways@4.2.3/dev.shadowsoffire.gateways.gate.Wave.lambda$spawnRewards$2(Wave.java:72)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/gateways@4.2.3/dev.shadowsoffire.gateways.gate.Wave.spawnRewards(Wave.java:72)
	at TRANSFORMER/gateways@4.2.3/dev.shadowsoffire.gateways.entity.NormalGatewayEntity.completeWave(NormalGatewayEntity.java:54)
	at TRANSFORMER/gateways@4.2.3/dev.shadowsoffire.gateways.entity.GatewayEntity.m_8119_(GatewayEntity.java:197)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$145(Level.java)
	at TRANSFORMER/neruina@1.3.0/com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$bdf000$catchTickingEntities(Level.java:3540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)

**Comment by SiverDX** [comment]
Might be better to ask the Library of Exile dev

Gateways damages the entity with `1` damage and somehow `EntityDmgStatsData` from Library of Exile ends up with a value of Infinity
