### ISSUE TITLE
Gateways will not spawn mobs with custom name nbt, just the mob

### ISSUE THREAD

**Issue by Xplodin** [Shadows-of-Fire/GatewaysToEternity#56]
Failed to parse entity custom name dingle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:72) ~[gson-2.10.jar%23107!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.util.GsonHelper.m_13798_(GsonHelper.java:568) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.network.chat.Component$Serializer.m_130701_(Component.java:401) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1725) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.entity.EntityType.m_185988_(EntityType.java:532) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.entity.EntityType.m_20642_(EntityType.java:529) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.entity.EntityType.m_20669_(EntityType.java:607) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:563) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at dev.shadowsoffire.gateways.gate.WaveEntity$StandardWaveEntity.createEntity(WaveEntity.java:93) ~[GatewaysToEternity-1.20.1-4.2.5.jar%231015!/:4.2.5]
	at dev.shadowsoffire.gateways.gate.Wave.spawnWaveEntity(Wave.java:97) ~[GatewaysToEternity-1.20.1-4.2.5.jar%231015!/:4.2.5]
	at dev.shadowsoffire.gateways.gate.Wave.spawnWave(Wave.java:58) ~[GatewaysToEternity-1.20.1-4.2.5.jar%231015!/:4.2.5]
	at dev.shadowsoffire.gateways.entity.GatewayEntity.startNextWave(GatewayEntity.java:247) ~[GatewaysToEternity-1.20.1-4.2.5.jar%231015!/:4.2.5]
	at dev.shadowsoffire.gateways.entity.GatewayEntity.m_8119_(GatewayEntity.java:207) ~[GatewaysToEternity-1.20.1-4.2.5.jar%231015!/:4.2.5]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:11169) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$epf000$observable$onTickNonPassenger(ServerLevel.java:11185) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.level.Level.mixinextras$bridge$accept$180(Level.java) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.0-forge+1.20.1.jar%231156!/:?]
	at net.minecraft.world.level.Level.wrapOperation$hmp000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:10040) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231366!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:602) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.Streams.parse(Streams.java:47) ~[gson-2.10.jar%23107!/:?]
	... 31 more

{
            "entities": [
                {
                    "entity": "minecraft:endermite",
					"nbt": "{CustomName:\"dingle\"}"
                }
            ],

It will not work even no matter how its put, itll just spawn the mob without a name

**Comment by Shadows-of-Fire** [comment]
This error means the nbt data you set as the custom name field is invalid.  It has to be a legal mc chat component, of which a plaintext string is not.

You can use a tool like mcstacker to generate the appropriate nbt data.
